site_name: D&A
site_author: "Brother Rain"

pages:
- "Home": 'index.md'
- "Data Structures":
  - "Arrays": 'd_array.md'
- "Algorithms":
  - "Graph Theory": 'a_graph_theory.md'

markdown_extensions:
    - footnotes

extra_css:
  - css/book.css
  - css/course.css
  - css/video.css
extra_javascript:
  - js/underscore.js
  - js/gspreadsheet.js
  - js/book.js
  - js/course.js
  - js/video.js
